import { Download, FileUp, LockKeyhole, Trash2 } from 'lucide-react'
import { Button } from '@/components/ui/button.jsx'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card.jsx'

export function Profile({ userData, stats, onExport, onImportFile, onReset, resetPending, setResetPending }) {
  return (
    <main className="p-6 pb-24"><header className="mb-5 text-center"><h1 className="text-2xl font-bold text-slate-900">Perfil e dados</h1><p className="mt-1 text-sm text-slate-600">Controle simples dos seus dados neste dispositivo.</p></header>
      <Card className="mb-4"><CardHeader><CardTitle className="text-base">Suas informações</CardTitle></CardHeader><CardContent className="space-y-2 text-sm text-slate-700"><p><strong>Nome:</strong> {userData.profile.name}</p><p><strong>Idade:</strong> {userData.profile.age} anos</p><p><strong>Focos:</strong> {userData.profile.objectives.join(', ')}</p><p><strong>Início:</strong> {userData.startDate ? new Date(userData.startDate).toLocaleDateString('pt-BR') : '—'}</p><p><strong>Registros:</strong> {stats.totalDays}</p></CardContent></Card>
      <Card className="mb-4 border-sky-100"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><LockKeyhole className="h-5 w-5 text-sky-700" aria-hidden="true" />Privacidade e backup</CardTitle></CardHeader><CardContent className="space-y-4"><p className="text-sm leading-relaxed text-slate-600">Peso, humor, notas e hábitos ficam apenas no armazenamento deste navegador. Não há conta, nuvem ou sincronização entre aparelhos. Em computador compartilhado, use um perfil de navegador privado.</p><div className="grid gap-2"><Button type="button" variant="outline" onClick={onExport}><Download className="mr-2 h-4 w-4" aria-hidden="true" />Exportar meus dados</Button><label className="inline-flex h-10 cursor-pointer items-center justify-center rounded-md border border-slate-200 bg-white px-4 text-sm font-medium text-slate-700 shadow-xs transition hover:bg-slate-50"><FileUp className="mr-2 h-4 w-4" aria-hidden="true" />Importar backup<input className="sr-only" type="file" accept="application/json,.json" onChange={(event) => { const file = event.target.files?.[0]; if (file) onImportFile(file); event.target.value = '' }} /></label></div><p className="text-xs leading-relaxed text-slate-500">Importar um arquivo substitui os dados atuais após validação. Guarde o arquivo exportado em local seguro.</p></CardContent></Card>
      <Card className="border-red-100"><CardHeader><CardTitle className="text-base text-red-800">Apagar dados deste dispositivo</CardTitle></CardHeader><CardContent><p className="mb-4 text-sm leading-relaxed text-slate-600">Essa ação remove seu perfil, check-ins e metas deste navegador. Exporte um backup antes, se quiser preservá-los.</p>{resetPending ? <div className="rounded-xl bg-red-50 p-3"><p className="text-sm font-medium text-red-900">Confirmar exclusão definitiva dos dados locais?</p><div className="mt-3 flex gap-2"><Button type="button" variant="destructive" onClick={onReset}>Sim, apagar dados</Button><Button type="button" variant="outline" onClick={() => setResetPending(false)}>Cancelar</Button></div></div> : <Button type="button" variant="outline" className="w-full border-red-200 text-red-700 hover:bg-red-50 hover:text-red-800" onClick={() => setResetPending(true)}><Trash2 className="mr-2 h-4 w-4" aria-hidden="true" />Apagar meus dados</Button>}</CardContent></Card>
    </main>
  )
}
